name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OMNI_GH_KEY }}
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.OMNI_HOST }}
          REMOTE_USER: ${{ secrets.OMNI_USER }}
          TARGET: '~/caddy/site/jour.rest.quest/'
          EXCLUDE: '/dist/, /node_modules/'
